src/Web/ViewModels/QuoteViewModel.cs
using Nethereum.eShop.ApplicationCore.Entities;
using System;
using System.Collections.Generic;

namespace Nethereum.eShop.Web.ViewModels
{
    public class QuoteViewModel
    {
        public int QuoteId { get; set; }

        public string TransactionHash { get; set; }

        public DateTimeOffset QuoteDate { get; set; }
        public decimal Total { get; set; }
        public string Status { get; set; }
        public PostalAddress ShipTo { get; set; }

        public PostalAddress BillTo { get; set; }
        public List<QuoteItemViewModel> QuoteItems { get; set; } = new List<QuoteItemViewModel>();
    }
}

src/Web/Controllers/QuoteController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Nethereum.eShop.Web.Features.MyQuotes;
using Nethereum.eShop.Web.Features.QuoteDetails;
using System.Threading.Tasks;

namespace Nethereum.eShop.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize] // Controllers that mainly require Authorization still use Controller/View; other pages use Pages
    [Route("[controller]/[action]")]
    public class QuoteController : Controller
    {
        private readonly IMediator _mediator;

        public QuoteController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet()]
        public async Task<IActionResult> MyQuotes()
        {
            var viewModel = await _mediator.Send(new GetMyQuotes(User.Identity.Name));

            return View(viewModel);
        }

        [HttpGet("{quoteId}")]
        public async Task<IActionResult> Detail(int quoteId)
        {
            var viewModel = await _mediator.Send(new GetQuoteDetails(User.Identity.Name, quoteId));

            if (viewModel == null)
            {
                return BadRequest("No such quote found for this user.");
            }

            return View(viewModel);
        }
    }
}

src/Web/Views/Quote/Detail.cshtml
@model QuoteViewModel
@{
    ViewData["Title"] = "My Quotes";
}
@{
    ViewData["Title"] = "Quote Detail";
}

<div class="esh-orders-detail">
    <div class="container">
        <section class="esh-orders-detail-section">
            <article class="esh-orders-detail-titles row">
                <section class="esh-orders-detail-title col-xs-3">Order number</section>
                <section class="esh-orders-detail-title col-xs-3">Tx hash</section>
                <section class="esh-orders-detail-title col-xs-3">Date</section>
                <section class="esh-orders-detail-title col-xs-2">Total</section>
                <section class="esh-orders-detail-title col-xs-3">Status</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-3">@Model.QuoteId</section>
                <section class="esh-orders-detail-item col-xs-3">@Model.TransactionHash</section>
                <section class="esh-orders-detail-item col-xs-3">@Model.QuoteDate</section>
                <section class="esh-orders-detail-item col-xs-2">$@Model.Total.ToString("N2")</section>
                <section class="esh-orders-detail-item col-xs-3">@Model.Status</section>
            </article>
        </section>

        <section class="esh-orders-detail-section">
            <article class="esh-orders-detail-titles row">
                <section class="esh-orders-detail-title col-xs-12">Shipping Address</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-12">@Model.ShipTo?.Street</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-12">@Model.ShipTo?.City</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-12">@Model.ShipTo?.Country</section>
            </article>
        </section>

        <section class="esh-orders-detail-section">
            <article class="esh-orders-detail-titles row">
                <section class="esh-orders-detail-title col-xs-12">Billing Address</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-12">@Model.BillTo?.Street</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-12">@Model.BillTo?.City</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-12">@Model.BillTo?.Country</section>
            </article>
        </section>

        <section class="esh-orders-detail-section">
            <article class="esh-orders-detail-titles row">
                <section class="esh-orders-detail-title col-xs-12">ORDER DETAILS</section>
            </article>

            @for (int i = 0; i < Model.QuoteItems.Count; i++)
            {
                var item = Model.QuoteItems[i];
                <article class="esh-orders-detail-items esh-orders-detail-items--border row">
                    <section class="esh-orders-detail-item col-md-4 hidden-md-down">
                        <img class="esh-orders-detail-image" src="@item.PictureUrl">
                    </section>
                    <section class="esh-orders-detail-item esh-orders-detail-item--middle col-xs-3">@item.ProductName</section>
                    <section class="esh-orders-detail-item esh-orders-detail-item--middle col-xs-1">$ @item.UnitPrice.ToString("N2")</section>
                    <section class="esh-orders-detail-item esh-orders-detail-item--middle col-xs-1">@item.Units</section>
                    <section class="esh-orders-detail-item esh-orders-detail-item--middle col-xs-2">$ @Math.Round(item.Units * item.UnitPrice, 2).ToString("N2")</section>
                </article>
            }
        </section>

        <section class="esh-orders-detail-section esh-orders-detail-section--right">
            <article class="esh-orders-detail-titles esh-basket-titles--clean row">
                <section class="esh-orders-detail-title col-xs-9"></section>
                <section class="esh-orders-detail-title col-xs-2">TOTAL</section>
            </article>

            <article class="esh-orders-detail-items row">
                <section class="esh-orders-detail-item col-xs-9"></section>
                <section class="esh-orders-detail-item esh-orders-detail-item--mark col-xs-2">$ @Model.Total.ToString("N2")</section>
            </article>
        </section>
    </div>
</div>

src/Web/Views/Quote/MyQuotes.cshtml
@model IEnumerable<QuoteExcerptViewModel>
@{
    ViewData["Title"] = "My Quotes";
}

<div class="esh-orders">
    <div class="container">
        <h1>@ViewData["Title"]</h1>
        <article class="esh-orders-titles row">
            <section class="esh-orders-title col-md-1">Id</section>
            <section class="esh-orders-title col-md-4">Date</section>
            <section class="esh-orders-title col-md-1">PO</section>
            <section class="esh-orders-title col-md-1">Total</section>
            <section class="esh-orders-title col-md-3">Status</section>
            <section class="esh-orders-title col-md-2"></section>
        </article>
        @if (Model != null && Model.Any())
        {
            @foreach (var item in Model)
            {
    <article class="esh-orders-items row">
        <section class="esh-orders-item col-md-1">@Html.DisplayFor(modelItem => item.QuoteId)</section>
        <section class="esh-orders-item col-md-4">@Html.DisplayFor(modelItem => item.QuoteDate)</section>
        <section class="esh-orders-item col-md-1">@Html.DisplayFor(modelItem => item.PoNumber)</section>
        <section class="esh-orders-item col-md-1">$ @Html.DisplayFor(modelItem => item.Total)</section>
        <section class="esh-orders-item col-md-3">@Html.DisplayFor(modelItem => item.Status)</section>
        <section class="esh-orders-item col-md-1">
            <a class="esh-orders-link" asp-controller="Quote" asp-action="Detail" asp-route-quoteId="@item.QuoteId">Detail</a>
        </section>
        <section class="esh-orders-item col-md-1">
            @if (item.Status.ToLower() == "submitted")
            {
                <a class="esh-orders-link" asp-controller="Quote" asp-action="cancel" asp-route-quoteId="@item.QuoteId">Cancel</a>
            }
        </section>
    </article>

                @if (item.TransactionHash?.Length > 0)
                {
                    <article class="esh-orders-items row">
                        <section class="esh-orders-item col-md-12 text-center">
                            Tx Hash: @Html.DisplayFor(modelItem => item.TransactionHash)
                        </section>
                    </article>
                 }

             }
         }
        </div>
</div>